version: "3.9"

services:
  llama-cpp:
    build: .
    container_name: llama-cpp
    restart: always
    volumes:
      - /opt/rocm:/opt/rocm
    devices:
      - /dev/kfd
      - /dev/dri
    ports:
      - "8081:8081"
